### ISSUE TITLE
Build system refactor request

### ISSUE THREAD

**Issue by xqm32** [LPSim/backend#14]
Hi @zyr17, I think it's better to use a **modern** package manager/build system to maintain this project. For python, [Poetry](https://python-poetry.org) or [Hatch](https://hatch.pypa.io) can be a good choice. I have some experience on Poetry and do some try to refactor build system for `LPSim`. [Here](https://github.com/xqm32/backend/tree/use-poetry) is my refactored code, please help to check if this can work.

I have tested this refactor simply use `poetry run python -m pytest` and the sample random agent code with Python3.11 and Python3.12 on macOS.

To use poetry, you can follow the Poetry's [documentation](https://python-poetry.org/docs/#installation). I recommend to use official installer `curl -sSL https://install.python-poetry.org | python3 -`, but you can also use a standalone `pipx` install it if you prefer.

With poetry installed, run the following commands to install dependencies and create a virtual environment:

```sh
poetry install
```

You can use `poetry run <SOME_COMMAND>` to run commands in virtual environment. Also you can use `poetry shell` to activate an interactive virtual environment.

## Related Links

- https://github.com/xqm32/backend/tree/use-poetry
- https://python-poetry.org
- https://hatch.pypa.io

**Comment by zyr17** [comment]
Thank you for your suggestion! I will check your branch and work on it in the following weeks. (Maybe after 4.3 release, as there are too many new cards need to implement...)

**Comment by zyr17** [comment]
Currently I use `setuptools-scm` to control package versions and GitHub Actions to automatically publish with new tags. I've searched a while for replacement of this plugin with poetry, but didn't find equivallents. Do you have any idea?

And the build system refactor is mainly focus to solve the problem in different Python version compatibility, am I right? If so, maybe an Action matrix is another solution?
