### ISSUE TITLE
Remove the import prefix `src.` from tests

### ISSUE THREAD

**Issue by xqm32** [LPSim/backend#57]
Since we are using `src` layout in this project, we can use `pip install .` and then simply import files from `lpsim` module, rather than import from the `src`. But there still a problem that some test files import module with `tests` prefix. They can network properly with the `pip install .` method, so we should also modify them.

**Comment by zyr17** [comment]
Do `pip install .` then run tests will make debugging slower, as we should re-install after minor changes on main codes. Using `PYTHONPATH` may be a better solution, currently when running tests and local servers by vscode, I added `${pwd}/src` to `PYTHONPATH` so we can use `import lpsim` directly.

**Comment by xqm32** [comment]
Hi @zyr17. We can use `pip install -e .` to install an editable version of `lpsim`, and do tests without re-install. This is the practice[^1] for `src` layout Python project.

[^1]: https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#tests-outside-application-code

**Comment by zyr17** [comment]
Got it! I will try this way and edit the test codes.
